language: php

services:
  - redis-server

php:
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script:
  - bin/atoum -d tests
